// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzlgfaedmmvynekixsjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bGdmYWVkbW12eW5la2l4c2p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTI4NTksImV4cCI6MjA2MjAyODg1OX0.3zbhXS9xdvxgil_z3KyPUxHzkPRzrH4YraDrUyIElik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);